spring:
  profiles:
    include:
      - aws
#      - local
      - prod
  servlet:
    multipart:
      max-file-size: 10MB

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
